---
title: "Searching through some R Datasets"
output: html_notebook
---

Find data with desired specifics from the next list of datasets. 

http://vincentarelbundock.github.io/Rdatasets/datasets.html

```{r}
library(dplyr)
library(tidyverse)
library(XML)

url <- "http://vincentarelbundock.github.io/Rdatasets/datasets.html"

data_df <- readHTMLTable(url, header = TRUE) # reading the web page

rdatasets <- data_df[[2]] # getting the data frame of datas 

# when reading the data column names have some unnecessary blank space 
# removing blank space
colnames(rdatasets) <- trimws(colnames(rdatasets))

head(rdatasets)
```


```{r}
rdatasets$Rows <- as.numeric(as.character(rdatasets$Rows))
rdatasets$Cols <- as.numeric(as.character(rdatasets$Cols))
```

### Install and load packages (Optional)

This is done for easy look at many datasets, and avoiding manualy installing and loading necessary packages

```{r}
# getting the names of unique packages
rdatasets %>% select(Package) %>% unique() -> pkgs

pkgs <- as.vector(t(pkgs)) # vector of all unique packages 

#install.packages("easypackages")
library(easypackages)


installed_pkgs <- as.data.frame(installed.packages()) # data frame with all installed packages and 
                                                     # some additional information about packages 
head(installed_pkgs$Package) # preview of a first few installed packages' names


# Installing packages that aren't already installed 
t_f <- pkgs %in% installed_pkgs$Package # logical vector to see which packages are already installed

# sum(t_f) = length(pkgs) means that all packages are already installed
if (sum(t_f) != length(pkgs)) install.packages(pkgs[!t_f]) # install packages that aren't already installed

# Loading packages
loaded_pkgs <- (.packages()) # list of already loaded packages

# loading packages that aren't already loaded 
suppressPackageStartupMessages(easypackages::libraries(pkgs[!(pkgs %in% loaded_pkgs)]))   # TRY SUPRESMESSAGES
```

Now you can easily check any data with help().

```{r}
# e.g.
help("dogs")
```

Or you can search through for a specific number of rows, columns, etc.

```{r}
# e.g. 
rdatasets %>% filter(Rows > 5 & Rows <= 30 & Cols == 3 & has_numeric==TRUE) %>% arrange(desc(Rows))
```



